name: Deploy AWS Infra

on:

  workflow_dispatch:

jobs:
    deploy-aws-infra:
        runs-on: ubuntu-latest
        permissions:
          id-token: write

        steps:
          - name: Checkout Code
            uses: actions/checkout@v2

          - name: Configure AWS Credentials 
            uses: aws-actions/configure-aws-credentials@v2
            with:
              role-to-assume: ${{ secrets.PIPELINE_ROLE }}
              aws-region: eu-west-1

          - name: Set up Terraform 
            uses: hashicorp/setup-terraform@v1
            with:
              terraform_wrapper: false

          - name: Terraform Init 
            run: terraform init
            working-directory: ./infra

          - name: Terraform Plan 
            run: terraform plan
            working-directory: ./infra

          - name: Terraform Apply 
            run: terraform apply -auto-approve
            working-directory: ./infra
          
          - name: Capture EKS Cluster Name
            run: |
              output=$(terraform output -json)
              echo "CLUSTER_NAME=$(echo "$output" | jq -r '.cluster_name.value')" >> $GITHUB_ENV
            working-directory: ./infra

          