name: Destroy AWS Infra

on:
  workflow_dispatch:

jobs:
  destroy-aws-infra:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials 
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.PIPELINE_ROLE }}
          aws-region: eu-west-1

      - name: Set up Terraform 
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Terraform Init Infra
        run: terraform init
        working-directory: ./infra

      - name: Terraform Destroy Infra Resources
        run: terraform destroy -auto-approve
        working-directory: ./infra
