name: Test Secrets

on:
  workflow_dispatch:

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    environment: tf-eks-argocd
    steps:
      - name: Check if secret is available
        run: |
          if [ -z "${{ secrets.PIPELINE_ROLE }}" ]; then
            echo "❌ PIPELINE_ROLE is NOT set or is empty"
          else
            echo "✅ PIPELINE_ROLE is set (value is masked)"
          fi
      - name: Check if IAM_USER is available
        run: |
          if [ -z "${{ secrets.IAM_USER }}" ]; then
            echo "❌ IAM_USER is NOT set or is empty"
          else
            echo "✅ IAM_USER is set (value is masked)"
          fi
      - name: Check if AWS_ACCOUNT_ID is available
        run: |
          if [ -z "${{ secrets.AWS_ACCOUNT_ID }}" ]; then
            echo "❌ AWS_ACCOUNT_ID is NOT set or is empty"
          else
            echo "✅ AWS_ACCOUNT_ID is set (value is masked)"
          fi