name: Test Secrets

on:
  workflow_dispatch:

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    environment: tf-eks-argocd
    steps:
      - name: Check if secret is available
        run: |
          if [ -z "${{ secrets.PIPELINE_ROLE }}" ]; then
            echo "❌ PIPELINE_ROLE is NOT set or is empty"
          else
            echo "✅ PIPELINE_ROLE is set (value is masked)"
          fi
